# Configuration file for training of Protein
# classification model

description: 'Try different networks'
mode: 'seq'
model/type: ['mAlexNet', 'AlexNet', 'LeNet5']
trainer/save_dir: [
                'eval/CNRParkEven/malexnet',
                'eval/CNRParkEven/alexnet',
                'eval/CNRParkEven/lenet5',
                ]
trainer/resume: [
    'train/CNRParkEven/malexnet/model_best.pth',
    'train/CNRParkEven/alexnet/model_best.pth',
    'train/CNRParkEven/lenet5/model_best.pth',
]

base:
    # Configuration file for training of parking lot
    # classification model
    test_img_path: '../datasets/CNRPark-Patches-150x150'
    test_img_labels: '../datasets/splits/CNRParkAB/odd.txt'

    batch_size: 64

    model:
        args:
            num_classes: 2

    trainer:
        save_dir: 'train/CNRParkEven/malexnet'
        epochs: 18
        save_period: 3
        monitor: 'max accuracy'
        n_gpu: 1
