# Configuration file for training of parking lot
# classification model
train_img_path: '../datasets/PATCHES'
train_img_labels: '../datasets/splits/CNRPark-EXT/train.txt'
val_img_path: '../datasets/PATCHES'
val_img_labels: '../datasets/splits/CNRPark-EXT/val.txt'
test_img_path: '../datasets/PATCHES'
test_img_labels: '../datasets/splits/CNRPark-EXT/test.txt'

batch_size: 64

optimizer:
    type: 'SGD'
    args:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0005

scheduler:
    step_size: 2
    gamma: 0.5

model:
    type: 'mAlexNet'
    args:
        num_classes: 2

trainer:
    save_dir: 'train/CNRPark-EXT/malexnet'
    epochs: 36
    save_period: 3
    monitor: 'max accuracy'
    n_gpu: 1