#!/usr/bin/bash
#SBATCH --job-name=PKLotDetection
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --time=01:00:00
#SBATCH --partition=biggpu
#SBATCH --gres=gpu:1

# Run training for mAlexNet, AlexNet and LeNet5 and plot metrics
./train.sh

# Evaluate the networks
./eval.sh
